### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 1843200 # 1280*720*2
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
# freeze_trainable_layers: 1
# freeze_trainable_modules: all
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
# deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: websight_toy
template: qwen2_vl
cutoff_len: 8192
max_samples: 9000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/websight/toy/3b
# output_dir: saves/mrweb/fulll
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
